### PR TITLE
Save in .png instead of .jpg

### PR DESCRIPTION
**Pull request by 0x1355**
Hey @nateraw,

I was waiting for the resuming feature to merge. Didn't want to muddle the waters.

I ran some comparisons on saving in .png versus .jpg. In general, png format has  smoother color gradients and less artifacts. This is especially obvious after upsampling.

See the example below. Both generated at 960x512 and then upsampled 4x. Screeshot at 100% zoom. png on the left and jpg on the right. Click to view full-size.

image

The only drawback of png is larger size. At default compression levels, png is 8-9mb at 4k resolution while jpg is at 500-750kb. But considering the compute and time spent on generating these images, I feel we should prioritize image quality over file size. 

I also tried different png compression levels. The visual difference is minimal so I went with the [default](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png).

What do you think?

### CODE REVIEW

**Comment by nateraw** [comment]
Nice!! Meant to look into this as well, but haven't had bandwidth. I think I'll go ahead an merge this after #45 . 

Would be nice to parametrize this too, but might be unnecessary (so we can do it in future if folks ask)

**Comment by 0x1355** [comment]
Thanks! Really looking forward to #45 !

**Comment by nateraw** [comment]
Merged! I can fix up this PR if you'd like

**Comment by 0x1355** [comment]
I think I fixed it but can you take a look just to be sure?

**Comment by nateraw** [comment]
only consideration I have on .jpg is that you wont be able to easily resume those from runs generated before this change hits.

**Comment by 0x1355** [comment]
Huh... As long as they don't pull the code or update the package in-between it would work. Anyway we can 'warn' the users?

**Comment by nateraw** [comment]
Yea...and package wasn't released at all since we added resume support so probably a non-issue for the most part. Will run this real quick as sanity check, then merge. If I feel adventurous, I'll parametrize it so folks dont run into issues w/ old runs

(CC @codefaux - this may effect you if resuming .jpg runs, so giving you a heads up)

**Comment by 0x1355** [comment]
[Feeling adventurous](https://www.youtube.com/watch?v=D5zkaAGbdCQ)? 

Forgive my shameless self-promotion but it is just the perfect moment.

**Comment by nateraw** [comment]
Video is so cool! Excellent applied use case there. Thank you for sharing!!

Merging this as is for now! found one small spot where I needed to add .png, other than that I left as is.

**Comment by 0x1355** [comment]
Thank you ser!

**Comment by codefaux** [comment]
Thanks for the heads up. I'll keep a stable local copy until this run is done. 46% after several days, still 'only' on a 1080ti lol. 

Can't see any reason to argue for jpg to remain as an option, but easy resume support for previous runs would be `check if first frame exists in either format when resuming, use that for this run but default to png` for me.

**Comment by nateraw** [comment]
@codefaux I'll see if I can add that real quick

**Pull request merged**
