### PR TITLE
Add utils and reuse functions in torch and flax pipelines

### PR DESCRIPTION
**Pull request by charlielito**
Added utils.py to reuse some functions in both pipelines (flax and torch)

### CODE REVIEW

**Comment by charlielito** [comment]
Just added he missing features for flax:
* Implemented negative_prompt in the flax pipeline
* Implemented image_generation for Flax to be used in the Gradio App

**Comment by nateraw** [comment]
Thanks again for a great contribution!! Read through the code in depth last night. Looks good I think - I'll get this approved and merged this week sometime...got a few projects I'm juggling rn.

This PR really reminds me I should close out #54 so we dont run into diffs with style changes applied, makes PR changes a bit harder to read. Not your fault, my fault.

---

**Unrelated:** By the way @charlielito - do you have a Twitter? I'd like to tweet about the TPU release + tag you if you have one.

**Comment by charlielito** [comment]
> This PR really reminds me I should close out #54 so we dont run into diffs with style changes applied, makes PR changes a bit harder to read. Not your fault, my fault.

Yeah, I know :( I tried to configure black (number of chars per line) to not change that much the already existing code. 

> **Unrelated:** By the way @charlielito - do you have a Twitter? I'd like to tweet about the TPU release + tag you if you have one.

For sure! my user is @charlielito42

**Review by nateraw — APPROVED** [review]
LGTM

**Pull request merged**
